app:
  integration:
    oko-crm:
      url: https://api.okocrm.com/v2/
      token: 0510599d43fb005883494861667b8c8c:ea6cb0d691bf40cc82f976fe8d761efe

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog/main.xml
    enabled: true
